modLoader="javafml"
loaderVersion="[37,)"
license="§7§lThe §4§lMIT §7§lLicence§r (MIT)"
issueTrackerURL="https://github.com/Cubicpath/CubicTools/issues"

[[mods]]
    modId = "cubicthings"
    version = "0.3.0"
    displayName = "§bCubic Things"
    updateJSONURL="https://gist.githubusercontent.com/Cubicpath/7549c5e1d4c97f4d82a3dc233f0f95d6/raw"
    displayURL="https://github.com/Cubicpath/CubicThings"
    logoFile="modbanner.png"
    credits="Forge, and the Modding Community!"
    authors = "Cubicpath"
    description = '''
    Random assortment of useful things made by Cubicpath.'''

[[dependencies.cubicthings]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cubicthings]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"
